### ISSUE TITLE
More options.

### ISSUE THREAD

**Issue by Piter432** [InternalError503/forget-it#1]
Nice to you, that some of Restart my Chrome's features are coming back in this one :) But I have some requests, and this request are more options to extension like:
- Option to choose to close all (and selected if it's possible) tabs after/before cleaning.
- Option to choose to close all (and selected too, if it's possible) windows after/before cleaning.
- Option to open a new clean window and/or tab after/before cleaning.

I added to all requests “after/before cleaning”, because I don't know, when all tabs and windows are closing and when the new clean window is opening (I don't want to lose my tabs and windows).

And, of course, I can translate this extension to Polish, but GitHub doesn't like some of Polish letters (I can't type some of them) :P

**Comment by InternalError503** [comment]
Hi @Piter432 

In its current state it will close all non private windows and tabs then based on the users settings for what data to purge it then purges that data and shows a notification at the end.

I will try to allot some time to this project to add an option to not close all windows and tabs as some users may just want to purge selected data but keep using there current session tabs and windows.

For an option to select what tabs to close that would require some type of interface to select the tabs then input that data into an array before processing then closing of the windows and tabs, This while do able could be rather bulky and really does not fit the scope under which this addon was created for, Though that being said if enough users were to request it i would gladly bend the rules for such a feature.

For the translating there are a few options available, You can copy the [raw file](https://raw.githubusercontent.com/InternalError503/forget-it/master/_locales/en_us/messages.json) then edit it in a text editor like [notepad++](https://notepad-plus-plus.org/) then using gitHub for windows or the online editor fork the project and make the changes (Github has drag n drop upload feature) then once the changes are made create a pull request.

If your unsure about git and pull requests i have a [thread here](https://8pecxstudios.com/Forums/viewtopic.php?f=13&t=1079) full of helpful information to get you started, While the information is about other projects the general rules and concepts are the same throughout.

**Comment by InternalError503** [comment]
Hi @Piter432

The next version **1.3** will include a new option to turn off the closing off all **Tabs** and **Windows**
If you still wish to help with a translation let me know and i will hold this versions release for a few days so it can be included in the release, Its more then ok if you can't or is too difficult as its not for everybody.

Kind regards

**Comment by Piter432** [comment]
Quick question: Can I translate extension's name or I shouldn't do that? :)

**Comment by InternalError503** [comment]
Hi @Piter432

Yes, The name can be safely translated.

**Comment by InternalError503** [comment]
Version 1.3, Was pushed to the release channel, So if you provide a translation it will be in the next released version :)

**Comment by Piter432** [comment]
Polish localization is ready to merge: https://github.com/InternalError503/forget-it/pull/5

However I think there's one string missing and it's called “Auto forget at set time”.

**Comment by InternalError503** [comment]
Hi @Piter432 
Thank you for the translation, Yea it appears that entity was not added to the localization, I will have when do that when i get home tomorrow, Thanks for letting me know.

**Comment by InternalError503** [comment]
Ok these changes have been merged and pushed to chrome web store, Forget it will automatically update to the new version once made available by google.

@Piter432 Massive thanks for this, Thank you.

**Comment by Piter432** [comment]
Another update of Polish localization: #6
